let enemyThemes = [
  'Sentient Dust Bunny',
  'Retired God of Pencils',
  'Chronospatial Cartographer',
  'Melancholy Fog',
  'Forgotten Melody Incarnate',
  'Gravity Anomaly Child',
  'Dream Weaver\'s Apprentice',
  'Philosophical Zombie (Literal)',
  'Quantum Entangled Twins',
  'Sentient Algorithm of Doubt',
  'Living Rust Monster',
  'Emotional Echo Collector',
  'Paradoxical Pacifist Warlord',
  'Symbiotic Constellation',
  'Sentient Weather Pattern',
  'Glitched NPC Hero',
  'Memory Eater\'s Shadow',
  'Reincarnated Bureaucrat',
  'Animate Origami Samurai',
  'Self-Aware Pun',
  'Cosmic Librarian\'s Pet',
  'Sentient Streetlight Poet',
  'Whispering Wallflower',
  'Reality Fabric Mender',
  'Abyssal Chef',
  'Living Ideology',
  'Sentient Traffic Jam',
  'Discarded Divine Weapon',
  'Conceptual Thief (Steals Ideas)',
  'Walking, Talking Metaphor',
  'Time-Lost Gardener',
  'Voice of the Silent',
  'Sentient Echo Chamber',
  'The Last Pure Metaphor',
  'Embodiment of "Oops"',
  'Gravity\'s Forgotten Child',
  'Sentient Existential Crisis',
  'Collector of Lost Socks',
  'Anthropomorphic Second Guess',
  'Living Fractal Pattern',
  'The Bard of Bad Luck',
  'Sentient Rumor Mill',
  'Retired Fairytale Monster',
  'Guardian of Lost Languages',
  'The Color Out of Spacetime',
  'Sentient Comma Splice',
  'Empathic Computer Virus',
  'Philosophical Germ',
  'The Taste of Regret',
  'Sentient Half-Finished Story',
  'Guardian of Mundanity',
  'The Echo of a Scream',
  'Sentient Coffee Stain',
  'Conceptual Armor Smith',
  'Walking Question Mark',
  'Embodiment of Nostalgia',
  'Retired Urban Legend',
  'The Last Optimist',
  'Sentient Plot Hole',
  'Memory of a Dead God',
  'Living Conspiracy Theory',
  'Anthropomorphic Déjà Vu',
  'The Sound of Silence',
  'Sentient Bureaucratic Loophole',
  'Dream Archaeologist',
  'Guardian of Lost Potential',
  'The Glitch in the Matrix',
  'Sentient Forgotten Password',
  'Embodiment of "Maybe"',
  'Living Urban Sprawl',
  'The Color of Fear',
  'Sentient Broken Promise',
  'Retired Mascot Character',
  'Guardian of Unwritten Rules',
  'The Taste of Victory',
  'Sentient Typo',
  'Philosophical Bacterium',
  'Living Musical Score',
  'Anthropomorphic Writer\'s Block',
  'The Last Believer',
  'Sentient Historical Footnote',
  'Memory of a Future Past',
  'Living Abstract Concept',
  'Guardian of Liminal Spaces',
  'The Glare of Disapproval',
  'Sentient Missed Connection',
  'Embodiment of Pure Chaos',
  'Retired Prophecy Fulfiller',
  'The Weight of Secrets',
  'Sentient Statistical Anomaly',
  'Philosophical Virus',
  'Living Haiku',
  'Anthropomorphic Existential Dread',
  'The Last Unknown',
  'Sentient Footnote Corrector',
  'Memory of a Perfect Day',
  'Living Moral Dilemma',
  'Guardian of Faded Photographs',
  'The Whisper of Doubt',
  'Sentient "What If?"',
  'Sentient Pocket Lint',
  'Galactic Hitchhiker\'s Guide (Literal)',
  'Time-Traveling Food Critic',
  'The Last Payphone',
  'Sentient Unanswered Prayer',
  'Dream Cartographer\'s Apprentice',
  'Embodiment of Awkward Silence',
  'Quantum Mechanic (Literal)',
  'Sentient Lost Chord',
  'Emotional Spectrum Trader',
  'Paradoxical Truth Seeker',
  'Symbiotic Urban Legend',
  'Sentient Public Bench',
  'Glitched Reality Tourist',
  'Memory Smuggler',
  'Reincarnated Skeptic',
  'Animate Bookmark',
  'Self-Aware Limerick',
  'Cosmic Janitor\'s Assistant',
  'Sentient Internet Troll (Reformed)',
  'Whispering Wind Chime',
  'Reality Patchwork Quilter',
  'Abyssal Gardener',
  'Living Moral Code',
  'Sentient Urban Decay',
  'Discarded Childhood Toy',
  'Conceptual Locksmith',
  'Walking, Talking Enigma',
  'Time-Lost Alchemist',
  'Voice of Forgotten Gods',
  'Sentient Echo Location',
  'The First Bad Joke',
  'Embodiment of "Why Not?"',
  'Gravity\'s Rebellious Child',
  'Sentient Existential Joy',
  'Collector of Lost Buttons',
  'Anthropomorphic Hindsight',
  'Living Geometric Proof',
  'The Bard of Good Fortune',
  'Sentient Chain Letter',
  'Retired Cryptid Hunter',
  'Guardian of Obsolete Technology',
  'The Color Out of Dreams',
  'Sentient Misplaced Modifier',
  'Empathetic Search Engine',
  'Philosophical Fungus',
  'The Smell of Rain',
  'Sentient Unfinished Symphony',
  'Guardian of Serendipity',
  'The Echo of Laughter',
  'Sentient Ketchup Packet',
  'Conceptual Architect',
  'Walking Conundrum',
  'Embodiment of Longing',
  'Retired Oracle',
  'The Last Storyteller',
  'Sentient Plot Twist',
  'Memory of a First Love',
  'Living Urban Myth',
  'Anthropomorphic Gut Feeling',
  'The Sound of Stars',
  'Sentient Software Update',
  'Dream Therapist',
  'Guardian of Lost Causes',
  'The Glitch in the System',
  'Sentient Forgotten Name',
  'Embodiment of "Perhaps"',
  'Living City Park',
  'The Color of Hope',
  'Sentient Broken Record',
  'Retired Villain\'s Sidekick',
  'Guardian of Unspoken Truths',
  'The Taste of Freedom',
  'Sentient Grammatical Error',
  'Philosophical Machine',
  'Living Blueprint',
  'Anthropomorphic Imposter Syndrome',
  'The Last Idealist',
  'Sentient Historical Inaccuracy',
  'Memory of a Lost Civilization',
  'Living Logical Fallacy',
  'Guardian of Hidden Pathways',
  'The Hum of Electricity',
  'Sentient Spam Email',
  'Embodiment of Pure Order',
  'Retired Monster Under Bed',
  'The Weight of Expectations',
  'Sentient Random Number Generator',
  'Philosophical Cloud Formation',
  'Living Poem',
  'Anthropomorphic Creative Spark',
  'The Last Keeper of Secrets',
  'Sentient Museum Exhibit',
  'Memory of a Forgotten War',
  'Living Riddle',
  'Guardian of Daydreams',
  'The Whisper of Wind',
  'Sentient Out-of-Office Reply',
  'Embodiment of Ambition',
  'Retired Guardian Angel',
  'The Spark of Invention',
  'Sentient Gluestick',
  'Wandering Philosopher-Chef',
  'Time-Displaced Historian',
  'The Last Paystub',
  'Sentient Unsent Letter',
  'Dreamscape Architect',
  'Embodiment of Indecision',
  'Quantum Entanglement Counselor',
  'Sentient Lost Luggage',
  'Emotional Alchemist',
  'Paradoxical Peacekeeper',
  'Symbiotic Rumor',
  'Sentient Park Statue',
  'Glitched Chronometer',
  'Memory Forger',
  'Reincarnated Librarian',
  'Animate Sticky Note',
  'Self-Aware Haiku',
  'Cosmic Mapmaker\'s Intern',
  'Sentient Spam Filter',
  'Whispering Library Book',
  'Reality Seamstress',
  'Abyssal Cartographer',
  'Living Fable',
  'Sentient Traffic Light',
  'Discarded Artist\'s Sketch',
  'Conceptual Weapon Smith',
  'Walking, Talking Paradox',
  'Time-Lost Botanist',
  'Voice of the Unheard',
  'Sentient Feedback Loop',
  'The First Misunderstanding',
  'Embodiment of "So What?"',
  'Gravity\'s Favorite Juggler',
  'Sentient Existential Relief',
  'Collector of Lost Memories',
  'Anthropomorphic Foresight',
  'Living Constellation Story',
  'The Bard of Misfortune',
  'Sentient Urban Sprout',
  'Retired Doomsday Prophet',
  'Guardian of Forgotten Crafts',
  'The Color Out of Sound',
  'Sentient Dangling Participle',
  'Empathetic Firewall',
  'Philosophical Rock Formation',
  'The Smell of Old Books',
  'Sentient Unplayed Game',
  'Guardian of Possibility',
  'The Echo of a Wish',
  'Sentient Used Tea Bag',
  'Conceptual Musician',
  'Walking Puzzle Box',
  'Embodiment of Curiosity',
  'Retired Secret Agent',
  'The Last Code Talker',
  'Sentient Unreliable Narrator',
  'Memory of a Shared Secret',
  'Living Folk Song',
  'Anthropomorphic Eureka Moment',
  'The Sound of Snowfall',
  'Sentient Autocorrect Error',
  'Dream Interpreter',
  'Guardian of Lost Dreams',
  'The Glitch in the Music',
  'Sentient Forgotten Tune',
  'Embodiment of "Why?"',
  'Living Abandoned Building',
  'The Color of Joy',
  'Sentient Scratched CD',
  'Retired Imaginary Friend',
  'Guardian of Unconventional Wisdom',
  'The Taste of Revenge',
  'Sentient Typographical Error (Intentional)',
  'Philosophical River Current',
  'Living Board Game Piece',
  'Anthropomorphic Stage Fright',
  'The Last Silent Film Star',
  'Sentient Historical Rumor',
  'Memory of a Distant Planet',
  'Living Oxymoron',
  'Guardian of Secret Gardens',
  'The Feel of Sunshine',
  'Sentient Error Message',
  'Embodiment of Pure Logic',
  'Retired Guardian of Thresholds',
  'The Weight of Knowledge',
  'Sentient Algorithm (Benevolent)',
  'Philosophical Breeze',
  'Living Musical Note',
  'Anthropomorphic Sense of Wonder',
  'The Last Map Maker',
  'Sentient Library Card',
  'Memory of a Lost Art',
  'Living Contradiction',
  'Guardian of Wild Ideas',
  'The Whisper of Leaves',
  'Sentient Automated Message',
  'Embodiment of Apathy',
  'Retired Cosmic Entity',
  'The Echo of Creation',
  'Sentient Button (Unpressed)',
  'Interdimensional Travel Agent',
  'Time-Loop Escapee',
  'The Last Dial-Up Modem',
  'Sentient Unread Email',
  'Nightmare Weaver',
  'Embodiment of Mild Annoyance',
  'Quantum Physicist\'s Cat (Possibly Alive)',
  'Sentient Forgotten Recipe',
  'Emotional Insulator',
  'Paradoxical Freedom Fighter',
  'Symbiotic Idea',
  'Sentient Graffiti Art',
  'Glitched Compass',
  'Memory Thief\'s Conscience',
  'Reincarnated Philosopher King',
  'Animate Shopping List',
  'Self-Aware Catchphrase',
  'Cosmic Tea Sommelier',
  'Sentient CAPTCHA',
  'Whispering Alleyway',
  'Reality Stress Tester',
  'Abyssal Linguist',
  'Living Code of Conduct',
  'Sentient Desert Mirage',
  'Discarded Love Letter',
  'Conceptual Artist (Literal)',
  'Walking, Talking Allegory',
  'Time-Lost Musician',
  'Voice of the Voiceless Animals',
  'Sentient Recurring Dream',
  'The First White Lie',
  'Embodiment of "Whatever."',
  'Gravity\'s Dance Partner',
  'Sentient Existential Puzzle',
  'Collector of Lost Laughter',
  'Anthropomorphic Intuition',
  'Living Stained Glass Window',
  'The Bard of Just Desserts',
  'Sentient Weed in Concrete',
  'Retired Fortune Cookie Writer',
  'Guardian of Lost Socks\' Mates',
  'The Color Out of Silence',
  'Sentient Run-on Sentence',
  'Empathetic Vending Machine',
  'Philosophical Storm Cloud',
  'The Smell of Burning Leaves',
  'Sentient Half-Built Bridge',
  'Guardian of Inner Peace',
  'The Echo of a Footstep',
  'Sentient Single Serving Container',
  'Conceptual Geographer',
  'Walking Thought Experiment',
  'Embodiment of Patience',
  'Retired Local Deity',
  'The Last Scribe',
  'Sentient Marginalia',
  'Memory of a Simple Kindness',
  'Living Tall Tale',
  'Anthropomorphic Brainstorm',
  'The Sound of a Heartbeat',
  'Sentient Glitchy Video Game',
  'Dream Archivist',
  'Guardian of Lost Hopes',
  'The Glitch in the Recipe',
  'Sentient Forgotten Password Hint',
  'Embodiment of "Tomorrow"',
  'Living Abandoned Theme Park',
  'The Color of Wisdom',
  'Sentient Broken Vase (Kintsugi)',
  'Retired Oracle\'s Interpreter',
  'Guardian of Unpopular Opinions',
  'The Taste of Betrayal',
  'Sentient Freudian Slip',
  'Philosophical Ocean Wave',
  'Living Chess Master\'s Strategy',
  'Anthropomorphic Performance Anxiety',
  'The Last Town Crier',
  'Sentient Historical Anachronism',
  'Memory of a Home',
  'Living Paradoxical Command',
  'Guardian of Secret Societies',
  'The Feel of Cool Water',
  'Sentient "404 Not Found"',
  'Embodiment of Pure Imagination',
  'Retired Keeper of Lost Things',
  'The Weight of Regret',
  'Sentient Algorithm (Chaotic Neutral)',
  'Philosophical Tree Root System',
  'Living Brushstroke',
  'Anthropomorphic Sense of Justice',
  'The Last Lighthouse Keeper',
  'Sentient Travel Brochure',
  'Memory of a Forgotten Melody',
  'Living Self-Fulfilling Prophecy',
  'Guardian of Whimsical Notions',
  'The Whisper of Conscience',
  'Sentient Voice Mail Greeting',
  'Embodiment of Boredom',
  'Retired Demigod of Small Inconveniences',
  'The Hum of the Universe',
  'Sentient Stray Shopping Cart',
  'Interdimensional Poet Laureate',
  'Time-Loop Therapist',
  'The Last Fax Machine',
  'Sentient Unopened Gift',
  'Nightmare Exterminator',
  'Embodiment of Extreme Politeness',
  'Quantum Entanglement Detective',
  'Sentient Misdelivered Package',
  'Emotional Amplifier',
  'Paradoxical Revolutionary',
  'Symbiotic Urban Garden',
  'Sentient Manhole Cover',
  'Glitched Translation Software',
  'Memory Sculptor',
  'Reincarnated Court Jester',
  'Animate To-Do List',
  'Self-Aware Acronym',
  'Cosmic Barista',
  'Sentient Firewall Breach',
  'Whispering Historical Marker',
  'Reality Debugger',
  'Abyssal Botanist',
  'Living Unwritten Law',
  'Sentient Optical Illusion',
  'Discarded Prototype',
  'Conceptual Mathematician',
  'Walking, Talking Hypothesis',
  'Time-Lost Astronomer',
  'Voice of the Silenced Majority',
  'Sentient Lucid Dream Character',
  'The First Shared Secret',
  'Embodiment of "Good Enough"',
  'Gravity\'s Unseen Assistant',
  'Sentient Existential Acceptance',
  'Collector of Lost Voices',
  'Anthropomorphic Premonition',
  'Living Architectural Blueprint',
  'The Bard of Second Chances',
  'Sentient Abandoned Mine Shaft',
  'Retired Museum Curator',
  'Guardian of Misunderstood Monsters',
  'The Color Out of Memory',
  'Sentient Comma (Oxford)',
  'Empathetic ATM',
  'Philosophical Ant Hill',
  'The Smell of Freshly Cut Grass',
  'Sentient Unfinished Painting',
  'Guardian of Quiet Contemplation',
  'The Echo of a Promise',
  'Sentient Single-Use Plastic',
  'Conceptual Historian',
  'Walking Moral Quandary',
  'Embodiment of Perseverance',
  'Retired Intergalactic Diplomat',
  'The Last Cartographer of Stars',
  'Sentient Footnote to History',
  'Memory of a Peaceful Moment',
  'Living Urban Legend (True)',
  'Anthropomorphic Déjà Rêvé',
  'The Sound of a Distant Train',
  'Sentient Corrupted File',
  'Dream Weaver\'s Nemesis',
  'Guardian of Lost Traditions',
  'The Glitch in the Timeline',
  'Sentient Forgotten Shopping List',
  'Embodiment of "Eventually"',
  'Living Ghost Town',
  'The Color of Truth',
  'Sentient Mended Clothing',
  'Retired Keeper of Oaths',
  'Guardian of Unspoken Agreements',
  'The Taste of Disappointment',
  'Sentient Spoonerism',
  'Philosophical Mountain Peak',
  'Living Board Game Rulebook',
  'Anthropomorphic Fear of Missing Out',
  'The Last Vaudeville Performer',
  'Sentient Historical Cover-Up',
  'Memory of a Sound',
  'Living Catch-22',
  'Guardian of Secret Passages',
  'The Feel of Soft Fur',
  'Sentient Loading Bar (Slow)',
  'Embodiment of Pure Potential',
  'Retired Doorkeeper of Worlds',
  'The Weight of the World (Figurative)',
  'Sentient Algorithm (Mischievous)',
  'Philosophical Snowflake Pattern',
  'Living Artistic Muse',
  'Anthropomorphic Sense of Direction (Poor)',
  'The Last Telegram Deliverer',
  'Sentient Travel Itinerary',
  'Memory of a Forgotten Scent',
  'Living Prophetic Dream',
  'Guardian of Lost Children\'s Toys',
  'The Whisper of Opportunity',
  'Sentient "Read Me" File',
  'Embodiment of Skepticism',
  'Retired God of Minor Annoyances',
  'The Silence Between Notes',
  'Sentient Chewing Gum Under Chair',
  'Dimensional Cartographer',
  'Time-Traveling Anthropologist',
  'The Last Vinyl Record',
  'Sentient Unanswered Question',
  'Nightmare Collector',
  'Embodiment of Overwhelming Enthusiasm',
  'Quantum Mechanic\'s Wrench',
  'Sentient Misheard Lyric',
  'Emotional Dampener Field',
  'Paradoxical Isolationist Leader',
  'Symbiotic Artistic Inspiration',
  'Sentient Pothole',
  'Glitched Prophecy',
  'Memory Eraser (Ethical)',
  'Reincarnated Storyteller',
  'Animate Doodled Margin Note',
  'Self-Aware Legal Disclaimer',
  'Cosmic Sommelier of Experiences',
  'Sentient Pop-Up Blocker',
  'Whispering Graffiti Tag',
  'Reality Consistency Checker',
  'Abyssal Philosopher',
  'Living Unspoken Rule',
  'Sentient Dust Storm',
  'Discarded Movie Prop',
  'Conceptual Linguist',
  'Walking, Talking Koan',
  'Time-Lost Inventor',
  'Voice of the Planet',
  'Sentient Shared Delusion',
  'The First Broken Promise',
  'Embodiment of "Who Cares?"',
  'Gravity\'s Unwilling Participant',
  'Sentient Existential Void (Friendly)',
  'Collector of Lost Time',
  'Anthropomorphic Hunch',
  'Living Tapestry of Events',
  'The Bard of Awkward Truths',
  'Sentient Moss Growth',
  'Retired Conspiracy Theorist (Proven Right)',
  'Guardian of Forgotten Knowledge',
  'The Color Out of Thought',
  'Sentient Split Infinitive',
  'Empathetic Smart Home Device',
  'Philosophical Raindrop',
  'The Smell of Old Paper',
  'Sentient Unfinished Novel',
  'Guardian of Unexpected Joy',
  'The Echo of a Goodbye',
  'Sentient Single Shoelace',
  'Conceptual Astronomer',
  'Walking Ethical Dilemma',
  'Embodiment of Resilience',
  'Retired Guardian of a Dead Star',
  'The Last Keeper of Flames',
  'Sentient Footnote\'s Footnote',
  'Memory of a Shared Dream',
  'Living Local Legend',
  'Anthropomorphic Impending Doom (Minor)',
  'The Sound of Crickets',
  'Sentient Blue Screen of Death',
  'Dreamscape Repairperson',
  'Guardian of Lost Skills',
  'The Glitch in the Art',
  'Sentient Forgotten Anniversary',
  'Embodiment of "Soon"',
  'Living Abandoned Factory',
  'The Color of Serenity',
  'Sentient Patched Tire',
  'Retired Prophetic Dreamer',
  'Guardian of Unconventional Solutions',
  'The Taste of Nostalgia',
  'Sentient Malapropism',
  'Philosophical River Stone',
  'Living Game Glitch Exploiter',
  'Anthropomorphic Social Awkwardness',
  'The Last Telegram Operator',
  'Sentient Historical Map (Inaccurate)',
  'Memory of a Taste',
  'Living Unsolvable Equation',
  'Guardian of Secret Recipes',
  'The Feel of Rough Bark',
  'Sentient "Buffering" Icon',
  'Embodiment of Pure Luck',
  'Retired Keeper of Gates',
  'The Weight of Silence',
  'Sentient Algorithm (Helpful but Annoying)',
  'Philosophical Spiderweb',
  'Living Unfinished Sculpture',
  'Anthropomorphic Sense of Humor (Dry)',
  'The Last Phone Booth User',
  'Sentient Travel Guide (Haunted)',
  'Memory of a Forgotten Place',
  'Living Ouroboros',
  'Guardian of Gentle Madness',
  'The Whisper of Regret',
  'Sentient Software Piracy Warning',
  'Embodiment of Calm',
  'Retired Oracle of Bad News',
  'The Hum of Ancient Machinery',
  'Sentient Discarded Battery',
  'Interdimensional Food Blogger',
  'Time-Loop Investigator',
  'The Last Typewriter Ribbon',
  'Sentient Undelivered Message',
  'Nightmare Interpreter',
  'Embodiment of Petty Revenge',
  'Quantum Entanglement Therapist',
  'Sentient Lost Key',
  'Emotional Conductor (Music)',
  'Paradoxical Peacemonger',
  'Symbiotic Urban Renewal Project',
  'Sentient Cracked Pavement',
  'Glitched Weather Report',
  'Memory Banker',
  'Reincarnated Skeptic\'s Ghost',
  'Animate Sticky Note Reminder',
  'Self-Aware Jingle',
  'Cosmic Tea Party Host',
  'Sentient Ad Blocker Exception',
  'Whispering Rune Stone',
  'Reality Auditor',
  'Abyssal Cartographer\'s Pen',
  'Living Social Contract',
  'Sentient Sand Dune',
  'Discarded Blueprint',
  'Conceptual Alchemist',
  'Walking, Talking Question',
  'Time-Lost Biologist',
  'Voice of the Silent Stars',
  'Sentient Groupthink Symptom',
  'The First Apology',
  'Embodiment of "Not Really"',
  'Gravity\'s Plaything',
  'Sentient Existential Dread (Manageable)',
  'Collector of Lost Chances',
  'Anthropomorphic Deja Visite',
  'Living Cave Painting',
  'The Bard of Understatement',
  'Sentient Lichen',
  'Retired Urban Explorer',
  'Guardian of Lost Art Forms',
  'The Color Out of Emotion',
  'Sentient Dangling Clause',
  'Empathetic Traffic Camera',
  'Philosophical Forest Fire',
  'The Smell of Petrichor',
  'Sentient Unfinished Song',
  'Guardian of Simple Pleasures',
  'The Echo of an Argument',
  'Sentient Bottle Cap',
  'Conceptual Linguist\'s Tool',
  'Walking Oxymoronic Statement',
  'Embodiment of Hope (Flickering)',
  'Retired Mythical Beast Tamer',
  'The Last Story Weaver',
  'Sentient Redacted Document',
  'Memory of a Shared Glance',
  'Living Local Custom',
  'Anthropomorphic Overthinking',
  'The Sound of a Pin Drop',
  'Sentient Corrupted Save File',
  'Dream Navigator',
  'Guardian of Lost Memories (Digital)',
  'The Glitch in the Code',
  'Sentient Forgotten Password Recovery Question',
  'Embodiment of "Later"',
  'Living Abandoned Spaceship',
  'The Color of Peace',
  'Sentient Repaired Object',
  'Retired Keeper of Secrets (Betrayed)',
  'Guardian of Unspoken Rules (Broken)',
  'The Taste of Success (Bittersweet)',
  'Sentient Pun (Unintentional)',
  'Philosophical Comet\'s Tail',
  'Living Game Mechanic (Exploitable)',
  'Anthropomorphic Fear of Heights',
  'The Last Morse Code Operator',
  'Sentient Historical Document (Forged)',
  'Memory of a Touch',
  'Living Logical Loophole',
  'Guardian of Secret Knowledge',
  'The Feel of Warm Sand',
  'Sentient "Please Wait" Message',
  'Embodiment of Pure Chaos (Contained)',
  'Retired Guardian of a Lost City',
  'The Weight of Words',
  'Sentient Algorithm (Confused)',
  'Philosophical Coral Reef',
  'Living Musical Instrument',
  'Anthropomorphic Sense of Belonging',
  'The Last Penny Farthing Rider',
  'Sentient Junk Mail Catalog',
  'Memory of a Forgotten Holiday',
  'Living Urban Micro-Forest',
  'Guardian of Forgotten Playgrounds',
  'The Whisper of Stars',
  'Sentient Unsubscribe Button',
  'Embodiment of Doubt (Constructive)',
  'Retired God of Lost Keys',
  'The Music of the Spheres (Literal)',
  'Sentient Used Napkin Sketch',
  'Dimensional Navigator\'s Compass',
  'Time-Traveling Sociologist',
  'The Last Cassette Tape',
  'Sentient Unresolved Plot Thread',
  'Nightmare Negotiator',
  'Embodiment of Righteous Indignation',
  'Quantum Entanglement Weaver',
  'Sentient Lost Earring',
  'Emotional Echo Locator',
  'Paradoxical Tyrant (Benevolent Intentions)',
  'Symbiotic Research Paper',
  'Sentient Speed Bump',
  'Glitched Historical Record',
  'Memory Curator for the Forgetful',
  'Reincarnated Satirist',
  'Animate Grocery Receipt',
  'Self-Aware Safety Warning',
  'Cosmic Event Planner',
  'Sentient Two-Factor Authentication',
  'Whispering Ancient Tree',
  'Reality Beta Tester',
  'Abyssal Historian',
  'Living Unwritten Constitution',
  'Sentient Heat Haze',
  'Discarded Musical Score',
  'Conceptual Physicist',
  'Walking, Talking Proverb',
  'Time-Lost Pharmacist',
  'Voice of the Natural World',
  'Sentient Inside Joke',
  'The First Forgiveness',
  'Embodiment of "Almost"',
  'Gravity\'s Awkward Dancer',
  'Sentient Existential Hope',
  'Collector of Lost Dreams (Physical Manifestations)',
  'Anthropomorphic Gut Instinct (Unreliable)',
  'Living Story Scroll',
  'The Bard of Uncomfortable Silences',
  'Sentient Puddle Reflection',
  'Retired Cryptozoologist',
  'Guardian of Vanishing Dialects',
  'The Color Out of Dreams (Nightmarish)',
  'Sentient Oxford Comma Advocate',
  'Empathetic Chatbot',
  'Philosophical Volcanic Eruption',
  'The Smell of Old Attic',
  'Sentient Half-Finished Painting (Masterpiece)',
  'Guardian of Everyday Magic',
  'The Echo of a Secret',
  'Sentient Take-Out Menu',
  'Conceptual Cartographer of Emotions',
  'Walking Logical Puzzle',
  'Embodiment of Self-Doubt',
  'Retired Guardian of Sacred Texts',
  'The Last Lamplighter',
  'Sentient Hidden Clause',
  'Memory of a Shared Meal',
  'Living Local Superstition',
  'Anthropomorphic Fear of Failure',
  'The Sound of a Distant Ocean',
  'Sentient System Crash Report',
  'Dream Journal (Living)',
  'Guardian of Lost Arts and Crafts',
  'The Glitch in the Perception',
  'Sentient Forgotten Holiday Card',
  'Embodiment of "Whenever"',
  'Living Abandoned Library',
  'The Color of Regret',
  'Sentient Kintsugi Bowl',
  'Retired Prophecy Analyst',
  'Guardian of Unconventional Heroes',
  'The Taste of Second Chances',
  'Sentient Mondegreen',
  'Philosophical Geyser',
  'Living Choose-Your-Own-Adventure Book',
  'Anthropomorphic Impatience',
  'The Last Drive-In Movie Projectionist',
  'Sentient Historical Forgery (Masterful)',
  'Memory of a Scent (Evocative)',
  'Living Unanswerable Question',
  'Guardian of Secret Ingredients',
  'The Feel of Cool Stone',
  'Sentient "Updating..." Message',
  'Embodiment of Pure Chance',
  'Retired Keeper of Legendary Weapons',
  'The Weight of Promises',
  'Sentient Algorithm (Self-Improving)',
  'Philosophical Aurora Borealis',
  'Living Unplayed Musical Instrument',
  'Anthropomorphic Sense of Direction (Perfect)',
  'The Last Telegraph Key',
  'Sentient Old Postcard',
  'Memory of a Forgotten Ritual',
  'Living Urban Greenway',
  'Guardian of Forgotten Lullabies',
  'The Whisper of Ancient Ruins',
  'Sentient "Terms and Conditions"',
  'Embodiment of Wonder (Childlike)',
  'Retired God of Misplaced Objects',
  'The Resonance of a Single Note',
  'Sentient Crumpled Paper Ball',
  'Dimensional Travel Blogger',
  'Time-Loop Escape Artist',
  'The Last Film Negative',
  'Sentient Unresolved Mystery',
  'Nightmare Sculptor (Creates Beauty from Fear)',
  'Embodiment of Sarcasm (Well-Intentioned)',
  'Quantum Entanglement Matchmaker',
  'Sentient Lost Puzzle Piece',
  'Emotional Frequency Tuner',
  'Paradoxical Dictator (Reluctant)',
  'Symbiotic Scientific Breakthrough',
  'Sentient Crosswalk Signal',
  'Glitched Weather Anomaly',
  'Memory Archivist of Lost Species',
  'Reincarnated Comedian (Bad Jokes)',
  'Animate Train Ticket (Expired)',
  'Self-Aware Elevator Music',
  'Cosmic Gardener of Stars',
  'Sentient VPN Tunnel',
  'Whispering Battlefield Memorial',
  'Reality Distortion Field Generator (Accidental)',
  'Abyssal Calligrapher',
  'Living Common Law Precedent',
  'Sentient Will-o\'-the-Wisp',
  'Discarded Scientific Hypothesis',
  'Conceptual Mathematician\'s Proof',
  'Walking, Talking Rumination',
  'Time-Lost Linguist (Ancient Languages)',
  'Voice of the Deep Ocean',
  'Sentient Social Media Trend',
  'The First Shared Hope',
  'Embodiment of "It Depends"',
  'Gravity\'s Comedian',
  'Sentient Existential Ennui',
  'Collector of Lost Opportunities',
  'Anthropomorphic Precognitive Flash',
  'Living Ancient Manuscript',
  'The Bard of Brutal Honesty',
  'Sentient Urban Wildlife',
  'Retired Keeper of Forbidden Lore',
  'Guardian of Endangered Sounds',
  'The Color Out of Joy (Manic)',
  'Sentient Em Dash Enthusiast',
  'Empathetic Spam Email Filter',
  'Philosophical Glacier Movement',
  'The Smell of New Beginnings',
  'Sentient Unfinished Symphony (Fragment)',
  'Guardian of Ephemeral Beauty',
  'The Echo of a Question',
  'Sentient Single Sock (Seeking Mate)',
  'Conceptual Architect of Dreams',
  'Walking Philosophical Argument',
  'Embodiment of Tenacity',
  'Retired Interdimensional Explorer',
  'The Last Star Chart Maker',
  'Sentient Erratum Slip',
  'Memory of a Shared Silence',
  'Living Local Dialect',
  'Anthropomorphic Creative Block (Overcome)',
  'The Sound of Gentle Rain',
  'Sentient Defragmenting Hard Drive',
  'Dream Weaver\'s Loom',
  'Guardian of Lost Recipes (Family Secrets)',
  'The Glitch in the Masterpiece',
  'Sentient Forgotten PIN Number',
  'Embodiment of "Now Or Never"',
  'Living Derelict Spaceship (Haunted)',
  'The Color of Truth (Blinding)',
  'Sentient Carefully Mended Toy',
  'Retired Keeper of Ancient Roads',
  'Guardian of Unspoken Desires',
  'The Taste of Lost Love',
  'Sentient Accidental Pun',
  'Philosophical Meteor Shower',
  'Living Rulebook Anomaly',
  'Anthropomorphic Fear of Intimacy',
  'The Last Radio Drama Actor',
  'Sentient Historical Myth (Debunked)',
  'Memory of a Melody (Half-Remembered)',
  'Living Unwinnable Argument',
  'Guardian of Secret Identities',
  'The Feel of Sun-Warmed Stone',
  'Sentient "Connection Lost" Message',
  'Embodiment of Pure Curiosity (Dangerous)',
  'Retired Guardian of a Sleeping Giant',
  'The Weight of Lost Potential',
  'Sentient Algorithm (Learning Empathy)',
  'Philosophical Shifting Sand Dune',
  'Living Unfinished Masterpiece',
  'Anthropomorphic Sense of Timing (Impeccable)',
  'The Last Switchboard Operator',
  'Sentient Old Map (Secret Routes)',
  'Memory of a Forgotten Promise',
  'Living Community Garden',
  'Guardian of Whispered Stories',
  'The Whisper of Forgotten Magic',
  'Sentient "Cookie Policy" Banner',
  'Embodiment of Resilience (Scarred)',
  'Retired God of Small Comforts',
  'The Harmony of Nature',
  'Sentient Discarded Sketchbook Page',
  'Dimensional Cartographer\'s Assistant',
  'Time-Traveling Ethicist',
  'The Last Betamax Tape',
  'Sentient Unasked Favor',
  'Nightmare Recycler',
  'Embodiment of Passive Aggression',
  'Quantum Entanglement Theorist (Disproven)',
  'Sentient Lost Piece of Jewelry',
  'Emotional Resonance Detector',
  'Paradoxical Anarchist (Orderly)',
  'Symbiotic Public Art Installation',
  'Sentient Uneven Sidewalk Tile',
  'Glitched Traffic Flow',
  'Memory Keeper for the Departed',
  'Reincarnated Cynic (Optimistic This Time)',
  'Animate Fortune Cookie Message',
  'Self-Aware Product Placement',
  'Cosmic Mixologist',
  'Sentient Privacy Setting',
  'Whispering Old Growth Forest',
  'Reality Quality Assurance',
  'Abyssal Astrologer',
  'Living Unspoken Agreement',
  'Sentient Aurora Australis',
  'Discarded Theatrical Costume',
  'Conceptual Poet',
  'Walking, Talking Moral Imperative',
  'Time-Lost Chef (Ancient Cuisine)',
  'Voice of the Mountains',
  'Sentient Viral Meme',
  'The First Shared Laugh',
  'Embodiment of "Probably Not"',
  'Gravity\'s Jester',
  'Sentient Existential Freedom',
  'Collector of Lost Innocence',
  'Anthropomorphic Gut Reaction (Accurate)',
  'Living Oral Tradition',
  'The Bard of Painful Truths',
  'Sentient Reflection in Water',
  'Retired Monster Hunter\'s Guide',
  'Guardian of Endangered Languages (Fictional)',
  'The Color Out of Madness',
  'Sentient Semicolon Supporter',
  'Empathetic Customer Service AI',
  'Philosophical Volcanic Vent',
  'The Smell of Home Cooking (Long Past)',
  'Sentient Unfinished Quest Log',
  'Guardian of Fleeting Moments',
  'The Echo of a Choice',
  'Sentient Used Bookstore Smell',
  'Conceptual Biologist of Dreams',
  'Walking Ethical Gray Area',
  'Embodiment of Stubbornness',
  'Retired Guardian of a Lost Civilization\'s Tech',
  'The Last Keeper of Oral Histories',
  'Sentient Marginal Note (Critical)',
  'Memory of a Shared Failure',
  'Living Local Ghost Story (Real)',
  'Anthropomorphic Fear of the Unknown',
  'The Sound of Crackling Fire',
  'Sentient Corrupted Data Packet',
  'Dream Interpreter\'s Muse',
  'Guardian of Lost Family Recipes',
  'The Glitch in the Reflection',
  'Sentient Forgotten WiFi Password',
  'Embodiment of "One Day"',
  'Living Abandoned Carnival',
  'The Color of Despair',
  'Sentient Lovingly Repaired Book',
  'Retired Prophecy Scribe',
  'Guardian of Unsung Heroes',
  'The Taste of Betrayal (Self-Inflicted)',
  'Sentient Freudian Slip (Revealing)',
  'Philosophical Deep Sea Current',
  'Living Interactive Fiction Character',
  'Anthropomorphic Impatience (Explosive)',
  'The Last Silent Movie Accompanist',
  'Sentient Historical Hoax (Believed)',
  'Memory of a Touch (Unwanted)',
  'Living Unbreakable Vow',
  'Guardian of Secret Sanctuaries',
  'The Feel of Cool Metal',
  'Sentient "System Error" Sound',
  'Embodiment of Pure Joy (Infectious)',
  'Retired Keeper of Cosmic Balance',
  'The Weight of Unspoken Words',
  'Sentient Algorithm (Philosophical)',
  'Philosophical Shifting Constellation',
  'Living Unfinished Opera',
  'Anthropomorphic Sense of Timing (Terrible)',
  'The Last Carrier Pigeon',
  'Sentient Old Family Photo',
  'Memory of a Forgotten Friend',
  'Living Local Folklore Character',
  'Guardian of Lost Childhood Games',
  'The Whisper of Forgotten Gods (Benevolent)',
  'Sentient "End User License Agreement"',
  'Embodiment of Curiosity (Cautious)',
  'Retired God of Second Thoughts',
  'The Rhythm of the City',
  'Sentient Forgotten Birthday Candle',
  'Dimensional Travel Documentarian',
  'Time-Loop Historian (Chronicling Repeats)',
  'The Last 8-Track Tape',
  'Sentient Unexpressed Emotion',
  'Nightmare Guardian (Protects from Nightmares)',
  'Embodiment of Polite Disagreement',
  'Quantum Entanglement Poet',
  'Sentient Lost Scarf',
  'Emotional Harmonizer',
  'Paradoxical Pacifist (Aggressively Peaceful)',
  'Symbiotic Urban Legend (Beneficial)',
  'Sentient Park Bench Philosopher',
  'Glitched Personal Assistant AI',
  'Memory Painter (Recreates Memories Visually)',
  'Reincarnated Stand-Up Comedian',
  'Animate Bus Schedule (Always Late)',
  'Self-Aware Warning Label',
  'Cosmic Barista\'s Regular',
  'Sentient Browser Cookie (Tracking You)',
  'Whispering Old Castle Wall',
  'Reality Proofreader',
  'Abyssal Librarian\'s Cat',
  'Living Unspoken Promise',
  'Sentient Rainbow After Storm',
  'Discarded Inventor\'s Journal',
  'Conceptual Musician\'s Instrument',
  'Walking, Talking Moral Compass (Faulty)',
  'Time-Lost Zoologist (Mythical Creatures)',
  'Voice of the Wilderness (Angry)',
  'Sentient Viral Video Star',
  'The First Shared Regret',
  'Embodiment of "We\'ll See"',
  'Gravity\'s Nemesis (Floats Occasionally)',
  'Sentient Existential Dread (Productive)',
  'Collector of Lost Potential (Attempts to Restore)',
  'Anthropomorphic Premonition (Vague)',
  'Living Ancient Map (Dynamic)',
  'The Bard of Inconvenient Truths',
  'Sentient Moss on North Side',
  'Retired Keeper of Lost Cities\' Secrets',
  'Guardian of Endangered Art Techniques',
  'The Color Out of Music (Synesthesia)',
  'Sentient Hyphen User',
  'Empathetic Security System',
  'Philosophical River Delta',
  'The Smell of Old Photographs',
  'Sentient Unfinished Epic Poem',
  'Guardian of Fleeting Thoughts',
  'The Echo of a Door Slamming',
  'Sentient Single Chopstick',
  'Conceptual Historian of the Future',
  'Walking Ethical Conundrum',
  'Embodiment of Patience (Wearing Thin)',
  'Retired Intergalactic Peacekeeper',
  'The Last Navigator by Stars (Urban)',
  'Sentient Addendum to a Will',
  'Memory of a Peaceful Protest',
  'Living Urban Legend (Self-Created)',
  'Anthropomorphic Deja Entendu',
  'The Sound of Distant Celebration',
  'Sentient Software Bug (Benign)',
  'Dream Weaver\'s Masterpiece',
  'Guardian of Lost Lullabies (Ancient)',
  'The Glitch in the Fabric of Time',
  'Sentient Forgotten Grocery Item',
  'Embodiment of "Just In Case"',
  'Living Ghost Ship',
  'The Color of Serendipity',
  'Sentient Mismatched Socks Pair',
  'Retired Keeper of Sacred Oaths (Broken)',
  'Guardian of Unspoken Gratitude',
  'The Taste of Hard-Earned Success',
  'Sentient Eggcorn',
  'Philosophical Mountain Range Silhouette',
  'Living Board Game Expansion',
  'Anthropomorphic Fear of Success',
  'The Last Circus Sideshow Performer',
  'Sentient Historical Revisionism',
  'Memory of a Touch (Healing)',
  'Living Catch-22 Solution',
  'Guardian of Secret Gardens (Urban)',
  'The Feel of Smooth Velvet',
  'Sentient "Loading Next Area" Screen',
  'Embodiment of Pure Playfulness',
  'Retired Doorkeeper of Dreams',
  'The Weight of Future Generations',
  'Sentient Algorithm (Trying to Understand Love)',
  'Philosophical Fossil Record',
  'Living Artistic Movement',
  'Anthropomorphic Sense of Direction (Innate)',
  'Bone Shaper',
  'Bone Sower',
  'Bone Starborn Hunter',
  'Bone Watcher',
  'Burning Alchemist',
  'Burning Artificer',
  'Burning Assassin',
  'Burning Bard',
  'Burning Blood Librarian',
  'Burning Hunter',
  'Burning Revenant',
  'Burning Sun Bard',
  'Burning Sun Prophet',
  'Burning Venom Oracle',
  'Burning Void Spy',
  'Burning Void Warden',
  'Celestial Ash Assassin',
  'Celestial Glass Beast',
  'Celestial Librarian',
  'Celestial Oracle',
  'Celestial Spy',
  'Celestial Steel Necromancer',
  'Celestial Stone Shaman',
  'Chained Glass Alchemist',
  'Chained Gold Witch',
  'Chained Hunter',
  'Chained Knight',
  'Chained Moon Scholar',
  'Chained Night Witch',
  'Chained Shadow Rogue',
  'Chained Sun Beast',
  'Chained Wind Nomad',
  'Chained Witch',
  'Crimson Alchemist',
  'Crimson Assassin',
  'Crimson Blood Assassin',
  'Crimson Bone Warden',
  'Crimson Frost Vigilante',
  'Crimson Frost Warlock',
  'Crimson Glass Hunter',
  'Crimson Gold Alchemist',
  'Crimson Iron Paladin',
  'Crimson Night Assassin',
  'Crimson Oracle',
  'Crimson Paladin',
  'Crimson Prophet',
  'Crimson Seer',
  'Crimson Steel Engineer',
  'Crimson Steel Prophet',
  'Crimson Steel Seer',
  'Crimson Storm Seer',
  'Crimson Thief',
  'Crimson Warlock',
  'Crimson Wind Necromancer',
  'Crimson Witch',
  'Cursed Alchemist',
  'Cursed Ash Spy',
  'Cursed Engineer',
  'Cursed Light Monk',
  'Cursed Paladin',
  'Cursed Sellsword',
  'Cursed Shadow Alchemist',
  'Cursed Spy',
  'Cursed Steel Artificer',
  'Cursed Steel Monk',
  'Cursed Sun Knight',
  'Cursed Thief',
  'Cursed Warlock',
  'Echoing Alchemist',
  'Echoing Artificer',
  'Echoing Bard',
  'Echoing Flame Librarian',
  'Echoing Iron Thief',
  'Echoing Light Revenant',
  'Echoing Necromancer',
  'Echoing Night Monk',
  'Echoing Revenant',
  'Echoing Rogue',
  'Echoing Scholar',
  'Echoing Shadow Shaman',
  'Echoing Star Revenant',
  'Echoing Steel Rogue',
  'Echoing Sun Seer',
  'Echoing Venom Hunter',
  'Echoing Void Monk',
  'Emerald Alchemist',
  'Emerald Beast',
  'Emerald Bone Engineer',
  'Emerald Bone Revenant',
  'Emerald Engineer',
  'Emerald Frost Knight',
  'Emerald Gold Paladin',
  'Emerald Monk',
  'Emerald Scholar',
  'Emerald Sellsword',
  'Emerald Storm Samurai',
  'Emerald Void Seer',
  'Emerald Void Warden',
  'Emerald Warlock',
  'Emerald Wind Vigilante',
  'Engineer of the Frost',
  'Engineer of the Night',
  'Engineer of the Shadow',
  'Engineer of the Star',
  'Engineer of the Steel',
  'Engineer of the Stone',
  'Eternal Ash Warden',
  'Eternal Blood Alchemist',
  'Eternal Bone Bard',
  'Eternal Frost Necromancer',
  'Eternal Frost Oracle',
  'Eternal Gold Thief',
  'Eternal Hunter',
  'Eternal Moon Samurai',
  'Eternal Nomad',
  'Eternal Oracle',
  'Eternal Sellsword',
  'Eternal Storm Artificer',
  'Eternal Sun Rogue',
  'Eternal Void Necromancer',
  'Eternal Wind Assassin',
  'Eternal Wind Golem',
  'Feral Beast',
  'Feral Flame Scribe',
  'Feral Glass Monk',
  'Feral Knight',
  'Feral Revenant',
  'Feral Scholar',
  'Feral Seer',
  'Feral Shadow Warlock',
  'Feral Storm Paladin',
  'Feral Vigilante',
  'Flame Bearer',
  'Flame Breaker',
  'Flame Caller',
  'Flame Celestial Monk',
  'Flame Crafter',
  'Flame Dancer',
  'Flame Echoing Scribe',
  'Flame Iron Warlock',
  'Flame Keeper',
  'Flame Mancer',
  'Flame Savage Shaman',
  'Flame Shattered Artificer',
  'Flame Sower',
  'Flame Starborn Alchemist',
  'Flame Walker',
  'Flame Watcher',
  'Forgotten Ash Golem',
  'Forgotten Assassin',
  'Forgotten Blood Scholar',
  'Forgotten Engineer',
  'Forgotten Glass Revenant',
  'Forgotten Golem',
  'Forgotten Monk',
  'Forgotten Necromancer',
  'Forgotten Oracle',
  'Forgotten Samurai',
  'Forgotten Shadow Warden',
  'Forgotten Star Shaman',
  'Forgotten Thief',
  'Forgotten Void Oracle',
  'Frost Binder',
  'Frost Breaker',
  'Frost Crafter',
  'Frost Echoing Golem',
  'Frost Gilded Necromancer',
  'Frost Hollow Prophet',
  'Frost Rider',
  'Frost Runic Golem',
  'Frost Timeless Witch',
  'Frost Walker',
  'Frost Whisperer',
  'Frost Whispering Artificer',
  'Frosted Alchemist',
  'Frosted Artificer',
  'Frosted Bard',
  'Frosted Frost Golem',
  'Frosted Glass Monk',
  'Frosted Glass Prophet',
  'Frosted Gold Thief',
  'Frosted Hunter',
  'Frosted Knight',
  'Frosted Librarian',
  'Frosted Monk',
  'Frosted Necromancer',
  'Frosted Samurai',
  'Frosted Venom Knight',
  'Frosted Void Seer',
  'Frosted Warden',
  'Ghostly Alchemist',
  'Ghostly Artificer',
  'Ghostly Engineer',
  'Ghostly Flame Engineer',
  'Ghostly Hunter',
  'Ghostly Monk',
  'Ghostly Moon Scholar',
  'Ghostly Necromancer',
  'Ghostly Samurai',
  'Ghostly Seer',
  'Ghostly Shaman',
  'Ghostly Venom Nomad',
  'Ghostly Void Shaman',
  'Gilded Ash Sellsword',
  'Gilded Beast',
  'Gilded Flame Warlock',
  'Gilded Frost Alchemist',
  'Gilded Glass Prophet',
  'Gilded Gold Nomad',
  'Gilded Golem',
  'Gilded Librarian',
  'Gilded Light Seer',
  'Gilded Light Vigilante',
  'Gilded Oracle',
  'Gilded Paladin',
  'Gilded Samurai',
  'Gilded Sellsword',
  'Gilded Steel Thief',
  'Gilded Storm Prophet',
  'Glass Bringer',
  'Glass Crafter',
  'Glass Crimson Librarian',
  'Glass Dancer',
  'Glass Feral Beast',
  'Glass Haunted Assassin',
  'Glass Mancer',
  'Glass Sacred Oracle',
  'Glass Savage Thief',
  'Glass Seeker',
  'Glass Shaper',
  'Glass Shattered Samurai',
  'Glass Shattered Scribe',
  'Glass Sower',
  'Glass Timeless Samurai',
  'Glass Twilight Engineer',
  'Glass Whispering Assassin',
  'Glass Wielder',
  'Gold Ancient Monk',
  'Gold Bearer',
  'Gold Bringer',
  'Gold Dancer',
  'Gold Feral Samurai',
  'Gold Forgotten Oracle',
  'Gold Ghostly Beast',
  'Gold Hunter',
  'Gold Iron Vigilante',
  'Gold Keeper',
  'Gold Mechanical Librarian',
  'Gold Mechanical Vigilante',
  'Gold Obsidian Thief',
  'Gold Sacred Revenant',
  'Gold Seeker',
  'Gold Shaper',
  'Gold Smith',
  'Gold Sower',
  'Gold Walker',
  'Gold Watcher',
  'Gold Wielder',
  'Golem of the Flame',
  'Golem of the Frost',
  'Golem of the Light',
  'Golem of the Star',
  'Golem of the Storm',
  'Golem of the Venom',
  'Haunted Bard',
  'Haunted Beast',
  'Haunted Glass Scholar',
  'Haunted Glass Spy',
  'Haunted Hunter',
  'Haunted Knight',
  'Haunted Light Engineer',
  'Haunted Monk',
  'Haunted Necromancer',
  'Haunted Night Knight',
  'Haunted Night Monk',
  'Haunted Samurai',
  'Haunted Shadow Sellsword',
  'Haunted Star Thief',
  'Haunted Sun Scribe',
  'Haunted Sun Spy',
  'Haunted Thief',
  'Haunted Venom Seer',
  'Haunted Vigilante',
  'Haunted Wind Golem',
  'Haunted Wind Oracle',
  'Hollow Ash Samurai',
  'Hollow Beast',
  'Hollow Moon Witch',
  'Hollow Night Nomad',
  'Hollow Oracle',
  'Hollow Samurai',
  'Hollow Scholar',
  'Hollow Scribe',
  'Hollow Seer',
  'Hollow Storm Alchemist',
  'Hollow Venom Seer',
  'Hollow Vigilante',
  'Hunter of the Flame',
  'Hunter of the Frost',
  'Hunter of the Glass',
  'Hunter of the Gold',
  'Hunter of the Iron',
  'Hunter of the Moon',
  'Hunter of the Night',
  'Hunter of the Star',
  'Hunter of the Steel',
  'Hunter of the Storm',
  'Hunter of the Sun',
  'Hunter of the Venom',
  'Hunter of the Wind',
  'Iron Ash Scribe',
  'Iron Beast',
  'Iron Caller',
  'Iron Celestial Vigilante',
  'Iron Glass Alchemist',
  'Iron Nomad',
  'Iron Prophet',
  'Iron Revenant',
  'Iron Samurai',
  'Iron Savage Monk',
  'Iron Seeker',
  'Iron Shadow Librarian',
  'Iron Shadow Oracle',
  'Iron Smith',
  'Iron Spy',
  'Iron Star Knight',
  'Iron Star Vigilante',
  'Iron Timeless Librarian',
  'Iron Twilight Warden',
  'Iron Walker',
  'Iron Wandering Samurai',
  'Iron Whispering Warden',
  'Iron Wielder',
  'Knight of the Ash',
  'Knight of the Blood',
  'Knight of the Flame',
  'Knight of the Frost',
  'Knight of the Gold',
  'Knight of the Stone',
  'Knight of the Sun',
  'Librarian of the Blood',
  'Librarian of the Frost',
  'Librarian of the Light',
  'Librarian of the Moon',
  'Librarian of the Stone',
  'Light Bearer',
  'Light Binder',
  'Light Breaker',
  'Light Bringer',
  'Light Caller',
  'Light Chained Knight',
  'Light Crimson Spy',
  'Light Echoing Beast',
  'Light Emerald Revenant',
  'Light Eternal Bard',
  'Light Forgotten Scribe',
  'Light Ghostly Monk',
  'Light Ghostly Necromancer',
  'Light Haunted Paladin',
  'Light Hollow Nomad',
  'Light Hunter',
  'Light Iron Bard',
  'Light Mancer',
  'Light Mechanical Revenant',
  'Light Obsidian Assassin',
  'Light Sacred Beast',
  'Light Seeker',
  'Light Shattered Rogue',
  'Light Smith',
  'Light Sower',
  'Light Starborn Paladin',
  'Light Timeless Shaman',
  'Light Twilight Scholar',
  'Light Wandering Shaman',
  'Light Wandering Warlock',
  'Light Watcher',
  'Light Whisperer',
  'Light Wielder',
  'Mechanical Alchemist',
  'Mechanical Librarian',
  'Mechanical Monk',
  'Mechanical Moon Spy',
  'Mechanical Nomad',
  'Mechanical Revenant',
  'Mechanical Rogue',
  'Mechanical Scholar',
  'Mechanical Sellsword',
  'Mechanical Shaman',
  'Mechanical Star Scribe',
  'Mechanical Stone Revenant',
  'Mechanical Void Sellsword',
  'Mechanical Wind Knight',
  'Monk of the Ash',
  'Monk of the Blood',
  'Monk of the Frost',
  'Monk of the Light',
  'Monk of the Night',
  'Monk of the Steel',
  'Monk of the Storm',
  'Monk of the Void',
  'Moon Bearer',
  'Moon Chained Shaman',
  'Moon Echoing Samurai',
  'Moon Forgotten Revenant',
  'Moon Haunted Alchemist',
  'Moon Hunter',
  'Moon Mancer',
  'Moon Rider',
  'Moon Runic Necromancer',
  'Moon Seeker',
  'Moon Singer',
  'Moon Sower',
  'Moon Wandering Alchemist',
  'Moon Whispering Necromancer',
  'Moon Whispering Seer',
  'Moon Wielder',
  'Necromancer of the Blood',
  'Necromancer of the Flame',
  'Necromancer of the Frost',
  'Necromancer of the Glass',
  'Necromancer of the Iron',
  'Necromancer of the Light',
  'Necromancer of the Moon',
  'Necromancer of the Steel',
  'Necromancer of the Venom',
  'Necromancer of the Wind',
  'Night Ancient Nomad',
  'Night Celestial Shaman',
  'Night Chained Nomad',
  'Night Crafter',
  'Night Dancer',
  'Night Hollow Samurai',
  'Night Keeper',
  'Night Mancer',
  'Night Rider',
  'Night Seeker',
  'Night Shaper',
  'Night Singer',
  'Night Watcher',
  'Nomad of the Bone',
  'Nomad of the Flame',
  'Nomad of the Glass',
  'Nomad of the Gold',
  'Nomad of the Shadow',
  'Nomad of the Stone',
  'Nomad of the Venom',
  'Nomad of the Wind',
  'Obsidian Artificer',
  'Obsidian Assassin',
  'Obsidian Blood Prophet',
  'Obsidian Frost Beast',
  'Obsidian Glass Hunter',
  'Obsidian Moon Nomad',
  'Obsidian Night Prophet',
  'Obsidian Rogue',
  'Obsidian Star Scholar',
  'Obsidian Void Prophet',
  'Obsidian Warlock',
  'Obsidian Wind Thief',
  'Oracle of the Ash',
  'Oracle of the Blood',
  'Oracle of the Bone',
  'Oracle of the Frost',
  'Oracle of the Moon',
  'Oracle of the Star',
  'Paladin of the Gold',
  'Paladin of the Iron',
  'Paladin of the Light',
  'Paladin of the Moon',
  'Paladin of the Stone',
  'Phantom Alchemist',
  'Phantom Ash Librarian',
  'Phantom Ash Sellsword',
  'Phantom Beast',
  'Phantom Gold Rogue',
  'Phantom Knight',
  'Phantom Night Seer',
  'Phantom Night Warlock',
  'Phantom Shaman',
  'Phantom Spy',
  'Phantom Stone Samurai',
  'Phantom Vigilante',
  'Phantom Wind Sellsword',
  'Prophet of the Bone',
  'Prophet of the Frost',
  'Prophet of the Glass',
  'Prophet of the Iron',
  'Prophet of the Moon',
  'Prophet of the Shadow',
  'Prophet of the Wind',
  'Revenant of the Glass',
  'Revenant of the Gold',
  'Revenant of the Iron',
  'Revenant of the Shadow',
  'Revenant of the Storm',
  'Revenant of the Venom',
  'Revenant of the Void',
  'Rogue of the Flame',
  'Rogue of the Light',
  'Rogue of the Moon',
  'Rogue of the Night',
  'Rogue of the Shadow',
  'Rogue of the Star',
  'Rogue of the Sun',
  'Rogue of the Venom',
  'Rogue of the Void',
  'Rogue of the Wind',
  'Runic Artificer',
  'Runic Blood Knight',
  'Runic Bone Shaman',
  'Runic Glass Spy',
  'Runic Moon Knight',
  'Runic Necromancer',
  'Runic Night Nomad',
  'Runic Samurai',
  'Runic Shadow Warden',
  'Runic Spy',
  'Runic Steel Revenant',
  'Runic Sun Scholar',
  'Runic Thief',
  'Runic Venom Oracle',
  'Runic Vigilante',
  'Runic Warlock',
  'Runic Witch',
  'Sacred Assassin',
  'Sacred Beast',
  'Sacred Flame Hunter',
  'Sacred Golem',
  'Sacred Light Oracle',
  'Sacred Oracle',
  'Sacred Paladin',
  'Sacred Prophet',
  'Sacred Revenant',
  'Sacred Rogue',
  'Sacred Star Scribe',
  'Sacred Storm Witch',
  'Sacred Sun Alchemist',
  'Sacred Vigilante',
  'Samurai of the Ash',
  'Samurai of the Flame',
  'Samurai of the Glass',
  'Samurai of the Light',
  'Samurai of the Moon',
  'Samurai of the Star',
  'Samurai of the Storm',
  'Savage Bone Bard',
  'Savage Frost Knight',
  'Savage Frost Sellsword',
  'Savage Gold Prophet',
  'Savage Gold Witch',
  'Savage Golem',
  'Savage Hunter',
  'Savage Necromancer',
  'Savage Oracle',
  'Savage Revenant',
  'Savage Rogue',
  'Savage Shaman',
  'Savage Storm Warlock',
  'Savage Venom Revenant',
  'Savage Venom Samurai',
  'Savage Void Samurai',
  'Scholar of the Glass',
  'Scholar of the Moon',
  'Scholar of the Steel',
  'Scholar of the Void',
  'Scholar of the Wind',
  'Scribe of the Bone',
  'Scribe of the Light',
  'Scribe of the Shadow',
  'Scribe of the Stone',
  'Scribe of the Venom',
  'Seer of the Bone',
  'Seer of the Frost',
  'Seer of the Light',
  'Seer of the Storm',
  'Sellsword of the Blood',
  'Sellsword of the Flame',
  'Sellsword of the Moon',
  'Sellsword of the Night',
  'Sellsword of the Venom',
  'Shadow Bringer',
  'Shadow Celestial Revenant',
  'Shadow Celestial Rogue',
  'Shadow Crafter',
  'Shadow Cursed Spy',
  'Shadow Emerald Shaman',
  'Shadow Frosted Assassin',
  'Shadow Iron Hunter',
  'Shadow Keeper',
  'Shadow Obsidian Alchemist',
  'Shadow Rider',
  'Shadow Savage Librarian',
  'Shadow Seeker',
  'Shadow Shaper',
  'Shadow Timeless Scholar',
  'Shadow Walker',
  'Shaman of the Bone',
  'Shaman of the Iron',
  'Shaman of the Light',
  'Shaman of the Moon',
  'Shaman of the Void',
  'Shattered Artificer',
  'Shattered Blood Samurai',
  'Shattered Blood Witch',
  'Shattered Flame Warlock',
  'Shattered Frost Warden',
  'Shattered Glass Vigilante',
  'Shattered Gold Prophet',
  'Shattered Librarian',
  'Shattered Nomad',
  'Shattered Revenant',
  'Shattered Seer',
  'Shattered Shadow Golem',
  'Shattered Void Shaman',
  'Shattered Warden',
  'Shattered Wind Prophet',
  'Shattered Wind Samurai',
  'Shattered Witch',
  'Spy of the Ash',
  'Spy of the Flame',
  'Spy of the Moon',
  'Spy of the Night',
  'Spy of the Steel',
  'Spy of the Storm',
  'Star Arcane Spy',
  'Star Arcane Warlock',
  'Star Bearer',
  'Star Caller',
  'Star Celestial Golem',
  'Star Celestial Witch',
  'Star Chained Scribe',
  'Star Cursed Scholar',
  'Star Dancer',
  'Star Feral Sellsword',
  'Star Forgotten Monk',
  'Star Frosted Samurai',
  'Star Frosted Shaman',
  'Star Ghostly Monk',
  'Star Keeper',
  'Star Mancer',
  'Star Phantom Warlock',
  'Star Sower',
  'Star Whisperer',
  'Star Whispering Bard',
  'Star Wielder',
  'Starborn Bard',
  'Starborn Blood Assassin',
  'Starborn Bone Necromancer',
  'Starborn Flame Golem',
  'Starborn Glass Spy',
  'Starborn Golem',
  'Starborn Librarian',
  'Starborn Necromancer',
  'Starborn Rogue',
  'Starborn Seer',
  'Starborn Spy',
  'Starborn Steel Beast',
  'Starborn Stone Spy',
  'Starborn Storm Librarian',
  'Starborn Vigilante',
  'Starborn Warden',
  'Starborn Warlock',
  'Starborn Witch',
  'Steel Bearer',
  'Steel Breaker',
  'Steel Caller',
  'Steel Crimson Monk',
  'Steel Frosted Necromancer',
  'Steel Gilded Scribe',
  'Steel Hollow Bard',
  'Steel Obsidian Scholar',
  'Steel Savage Artificer',
  'Steel Smith',
  'Steel Wielder',
  'Stone Arcane Paladin',
  'Stone Arcane Scribe',
  'Stone Bearer',
  'Stone Burning Warden',
  'Stone Caller',
  'Stone Chained Golem',
  'Stone Dancer',
  'Stone Eternal Hunter',
  'Stone Feral Monk',
  'Stone Frosted Vigilante',
  'Stone Gilded Nomad',
  'Stone Haunted Golem',
  'Stone Haunted Vigilante',
  'Stone Mechanical Engineer',
  'Stone Runic Assassin',
  'Stone Savage Warlock',
  'Stone Singer',
  'Stone Smith',
  'Stone Timeless Revenant',
  'Stone Watcher',
  'Stone Wielder',
  'Storm Ancient Sellsword',
  'Storm Bearer',
  'Storm Bringer',
  'Storm Burning Vigilante',
  'Storm Caller',
  'Storm Chained Beast',
  'Storm Chained Vigilante',
  'Storm Crafter',
  'Storm Dancer',
  'Storm Emerald Engineer',
  'Storm Feral Librarian',
  'Storm Ghostly Samurai',
  'Storm Gilded Prophet',
  'Storm Hollow Monk',
  'Storm Keeper',
  'Storm Mancer',
  'Storm Phantom Monk',
  'Storm Rider',
  'Storm Runic Bard',
  'Storm Sacred Thief',
  'Storm Savage Sellsword',
  'Storm Seeker',
  'Storm Shattered Artificer',
  'Storm Shattered Scholar',
  'Storm Singer',
  'Storm Twilight Alchemist',
  'Storm Walker',
  'Storm Whispering Scholar',
  'Storm Wielder',
  'Sun Bearer',
  'Sun Binder',
  'Sun Breaker',
  'Sun Burning Rogue',
  'Sun Chained Witch',
  'Sun Crafter',
  'Sun Crimson Revenant',
  'Sun Crimson Seer',
  'Sun Dancer',
  'Sun Emerald Samurai',
  'Sun Eternal Knight',
  'Sun Frosted Knight',
  'Sun Iron Shaman',
  'Sun Keeper',
  'Sun Mancer',
  'Sun Rider',
  'Sun Savage Shaman',
  'Sun Seeker',
  'Sun Shaper',
  'Sun Singer',
  'Sun Smith',
  'Sun Sower',
  'Sun Timeless Samurai',
  'Sun Timeless Seer',
  'Sun Whispering Sellsword',
  'Thief of the Bone',
  'Thief of the Flame',
  'Thief of the Glass',
  'Thief of the Moon',
  'Thief of the Star',
  'Thief of the Venom',
  'Timeless Assassin',
  'Timeless Engineer',
  'Timeless Flame Samurai',
  'Timeless Flame Witch',
  'Timeless Frost Golem',
  'Timeless Frost Nomad',
  'Timeless Gold Seer',
  'Timeless Golem',
  'Timeless Knight',
  'Timeless Nomad',
  'Timeless Shadow Revenant',
  'Timeless Spy',
  'Timeless Sun Nomad',
  'Timeless Thief',
  'Timeless Venom Beast',
  'Timeless Venom Monk',
  'Twilight Alchemist',
  'Twilight Artificer',
  'Twilight Assassin',
  'Twilight Bone Spy',
  'Twilight Glass Monk',
  'Twilight Golem',
  'Twilight Monk',
  'Twilight Moon Rogue',
  'Twilight Seer',
  'Twilight Sellsword',
  'Twilight Spy',
  'Twilight Star Assassin',
  'Twilight Star Librarian',
  'Twilight Star Witch',
  'Twilight Stone Warden',
  'Twilight Void Nomad',
  'Twilight Wind Hunter',
  'Venom Bearer',
  'Venom Breaker',
  'Venom Bringer',
  'Venom Cursed Necromancer',
  'Venom Echoing Beast',
  'Venom Echoing Paladin',
  'Venom Feral Scribe',
  'Venom Frosted Engineer',
  'Venom Frosted Sellsword',
  'Venom Haunted Beast',
  'Venom Hollow Shaman',
  'Venom Runic Necromancer',
  'Venom Runic Sellsword',
  'Venom Sacred Hunter',
  'Venom Seeker',
  'Venom Singer',
  'Venom Smith',
  'Venom Sower',
  'Venom Walker',
  'Venom Wandering Necromancer',
  'Venom Wandering Spy',
  'Venom Watcher',
  'Venom Whispering Paladin',
  'Venom Wielder',
  'Vigilante of the Blood',
  'Vigilante of the Flame',
  'Vigilante of the Night',
  'Vigilante of the Stone',
  'Void Ancient Shaman',
  'Void Bringer',
  'Void Celestial Oracle',
  'Void Hollow Monk',
  'Void Hunter',
  'Void Iron Paladin',
  'Void Obsidian Witch',
  'Void Rider',
  'Void Runic Rogue',
  'Void Shaper',
  'Void Smith',
  'Void Sower',
  'Void Watcher',
  'Void Whispering Rogue',
  'Void Wielder',
  'Wandering Glass Beast',
  'Wandering Necromancer',
  'Wandering Nomad',
  'Wandering Oracle',
  'Wandering Revenant',
  'Wandering Rogue',
  'Wandering Samurai',
  'Wandering Seer',
  'Wandering Star Oracle',
  'Wandering Stone Witch',
  'Wandering Storm Warden',
  'Wandering Warlock',
  'Warden of the Flame',
  'Warden of the Glass',
  'Warden of the Iron',
  'Warden of the Stone',
  'Warden of the Venom',
  'Warden of the Wind',
  'Warlock of the Flame',
  'Warlock of the Frost',
  'Warlock of the Gold',
  'Warlock of the Night',
  'Warlock of the Void',
  'Whispering Ash Spy',
  'Whispering Blood Oracle',
  'Whispering Blood Scholar',
  'Whispering Gold Beast',
  'Whispering Iron Vigilante',
  'Whispering Light Paladin',
  'Whispering Nomad',
  'Whispering Revenant',
  'Whispering Sellsword',
  'Whispering Storm Nomad',
  'Whispering Sun Witch',
  'Whispering Void Scribe',
  'Whispering Witch',
  'Wind Bringer',
  'Wind Caller',
  'Wind Celestial Spy',
  'Wind Chained Vigilante',
  'Wind Crafter',
  'Wind Cursed Warlock',
  'Wind Dancer',
  'Wind Echoing Oracle',
  'Wind Echoing Warden',
  'Wind Eternal Prophet',
  'Wind Hunter',
  'Wind Obsidian Witch',
  'Wind Phantom Thief',
  'Wind Sacred Artificer',
  'Wind Shaper',
  'Wind Singer',
  'Wind Smith',
  'Wind Sower',
  'Wind Walker',
  'Wind Watcher',
  'Wind Whispering Nomad',
  'Wind Whispering Vigilante',
  'Wind Wielder',
  'Witch of the Blood',
  'Witch of the Iron',
  'Witch of the Light',
  'Witch of the Shadow',
  'Witch of the Venom',
  'Alien Diplomat',
  'Haunted Librarian',
  'Clockwork Inventor',
  'Rogue AI',
  'Desert Nomad',
  'Sky Pirate',
  'Undercover Royalty',
  'Wandering Samurai',
  'Gothic Poet',
  'Cyberpunk Bounty Hunter',
  'Forgotten Deity',
  'Telepathic Child',
  'Steampunk Botanist',
  'Plague Doctor',
  'Ice Sorceress',
  'Lava Beast',
  'Ghost Detective',
  'Feral Child',
  'Junkyard Prophet',
  'Arcane Hacker',
  'Shadow Puppeteer',
  'Dragon Tamer',
  'Time Traveler',
  'Alien Zoologist',
  'Warrior Monk',
  'Elemental Guardian',
  'Sleepwalking Assassin',
  'Dream Architect',
  'Skyborne Oracle',
  'Necromancer Chef',
  'Cybernetic Farmer',
  'Night Circus Performer',
  'Celestial Cartographer',
  'Memory Thief',
  'Interdimensional Smuggler',
  'Lost Explorer',
  'Bone Collector',
  'Runaway Clone',
  'Virtual Idol',
  'Fire Dancer',
  'Mutant Revolutionary',
  'Psychic Detective',
  'Antique Dealer of Cursed Objects',
  'Sand Druid',
  'Bioluminescent Deep-Sea Diver',
  'Vampire Surgeon',
  'Starship Janitor',
  'Werewolf Librarian',
  'Radioactive Outlaw',
  'Puppet Medium',
  'Mad Geneticist',
  'Cloud Shepherd',
  'Moon Priestess',
  'Apocalyptic Park Ranger',
  'Forest Whisperer',
  'Cosmic Historian',
  'Steamship Gambler',
  'Demon Accountant',
  'Electric Monk',
  'Ocean Nomad',
  'Myth Collector',
  'Tundra Alchemist',
  'Reality Bender',
  'Pandemic Prophet',
  'Poison Bard',
  'Robot Therapist',
  'Coral Mage',
  'Flame Knight',
  'Plasmatic Sculptor',
  'Shark Whisperer',
  'Ethereal Artist',
  'Magnetic Monk',
  'Lava Harvester',
  'Cybernetic Witch',
  'Light Engineer',
  'Chaos Blacksmith',
  'Void Walker',
  'Junkyard King',
  'Mermaid Mechanic',
  'Dream Thief',
  'Sandstorm Prophet',
  'Cave Bard',
  'Biotech Healer',
  'Crystal Hunter',
  'Dinosaur Tamer',
  'Chrono Thief',
  'Jellyfish Biologist',
  'Firestorm Seer',
  'Glitch Sorcerer',
  'Mechanical Monk',
  'Stardust Sculptor',
  'Genetic Cartographer',
  'Acidic Knight',
  'Polar Hunter',
  'Spirit Gardener',
  'Neon Scribe',
  'Beast Sympath',
  'Virus Exorcist',
  'Android Monk',
  'Volcano Prophet'
]

export function getRandomTheme(): string {
  if (enemyThemes.length === 0) return "";
  const randomIndex = Math.floor(Math.random() * enemyThemes.length);
  return enemyThemes.splice(randomIndex, 1)[0];
}